version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - db
    links:
      - db:db

  db:
    container_name: db
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: on-failure
    volumes:
        - ./app/dump:/data/db